"""empty message

Revision ID: f0c2c737b69b
Revises: 
Create Date: 2022-10-15 18:44:21.972709

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f0c2c737b69b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'auth_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('comment', 'father_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('follow', 'follower_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('follow', 'followed_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('follow', 'followed_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('follow', 'follower_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('comment', 'father_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('comment', 'auth_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
